[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "manim-captcha"
version = "1.0.0"
description = "Animated visual captcha generation library using Manim."
authors = [
    { name="Jose Miguel Rios Rubio" }
]
readme = "README.md"
license = { text = "MIT" }
keywords = ["captcha", "manim", "animation", "video", "gif", "mp4"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
requires-python = ">=3.12"
dependencies = [
    "manim==0.19.2"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
