[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "manim-captcha"
version = "1.2.2"
description = "Animated visual captcha generation library using Manim."
authors = [
    { name="Jose Miguel Rios Rubio", email = "jrios.github@gmail.com" }
]
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["captcha", "manim", "animation", "video", "gif", "mp4"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux"
]
requires-python = ">=3.9"
dependencies = [
    "manim==0.19.2"
]

[project.urls]
Homepage = "https://github.com/J-Rios/manim-captcha"
Issues = "https://github.com/J-Rios/manim-captcha/issues"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
