#!/usr/bin/env bash
# Description: Run pyright for static type checks.

# Actual script directory path
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

TARGET_DIR="${DIR}/../src/manim_captcha"

# Show Header
echo "-------------------------------------------------"
echo " Static Type Checks "
echo "-------------------------------------------------"
echo ""

# Activate Virtual Environment
echo "Accesing Virtual Environment..."
source ${DIR}/../.venv/bin/activate || exit 1
echo ""

# Run static type checks
pyright "$TARGET_DIR"
echo ""

# Exit Virtual Environment
deactivate
echo "Static type checks completed"
echo ""

exit 0
