#!/usr/bin/env bash
# Description: Run Ruff to check code style.

# Actual script directory path
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

DIR_SRC="${DIR}/../src/manim_captcha"
DIR_TEST="${DIR}/../tests"

# Activate Virtual Environment
echo ""
echo "Accesing Virtual Environment..."
source ${DIR}/../.venv/bin/activate || exit 1
echo ""

# Run Code Style Check
echo "-------------------------------------------------"
echo " Checking Code Style - Source Files "
echo "-------------------------------------------------"
ruff check $DIR_SRC
echo ""
echo "-------------------------------------------------"
echo " Checking Code Style - Test Files "
echo "-------------------------------------------------"
ruff check $DIR_TEST
echo ""
echo "Cleanup..."
ruff clean
echo ""

# Exit Virtual Environment
deactivate
echo "Code Style check completed"
echo ""

exit 0
